version: "3.7"
volumes:
  pgdata:
services:
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres
